# Base image
FROM python:3.11-bullseye

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libnss3 libatk1.0-0 libatk-bridge2.0-0 libcups2 libx11-xcb1 \
    libxcomposite1 libxdamage1 libxrandr2 libgbm1 libasound2 \
    libpangocairo-1.0-0 libxshmfence1 libgtk-3-0 ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# 작업 디렉토리 설정
WORKDIR /app

# 의존성 파일 복사 및 설치
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Playwright 브라우저 설치 경로 설정
ENV PLAYWRIGHT_BROWSERS_PATH=/app/playwright-browsers
ENV REDIS_URL=${REDIS_URL}

# Playwright 및 브라우저 설치
RUN pip install playwright && playwright install --with-deps chromium

# Celery 애플리케이션 복사
COPY . .

# Celery worker 실행
CMD ["celery", "-A", "app.celeryconfig.celery_app", "worker", "--loglevel=info", "-c", "2", "--max-tasks-per-child=2"]