apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-wasp
  namespace: prod-service-maintenance
  labels:
    app: prod-wasp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-wasp
  template:
    metadata:
      labels:
        app: prod-wasp
    spec:
      imagePullSecrets:
      - name: docker
      containers:
      - env:
        - name: env
          value: prod
        envFrom:
          - secretRef:
              name: prod-secret
        name: prod-wasp
        image: docker.lezhin.com/wasp:TAG_ID
        ports:
        - containerPort: 8000
          name: 8000tcp1
          protocol: TCP
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
